apiVersion: k3d.io/v1alpha2
kind: Simple
name: kuiperdesk-cluster-az01
servers: 1
kubeAPI:
  hostIP: "0.0.0.0"
  hostPort: "6443"
image: rancher/k3s:latest
ports:
  - port: 80:80
    nodeFilters:
      - loadbalancer
  - port: 443:443
    nodeFilters:
      - loadbalancer
  - port: 5555:5555
    nodeFilters:
      - loadbalancer
  - port: 2379:2379
    nodeFilters:
      - loadbalancer
  - port: 2380:2380
    nodeFilters:
      - loadbalancer
  - port: 10250:10250
    nodeFilters:
      - loadbalancer
  - port: 10251:10251
    nodeFilters:
      - loadbalancer
  - port: 10252:10252
    nodeFilters:
      - loadbalancer
 - port: 10255:10255
   nodeFilters:
      - loadbalancer
options:
  k3d:
    wait: true
    timeout: "60s"
    disableLoadbalancer: false
    disableImageVolume: false
  k3s:
    extraServerArgs:
      - --tls-san=127.0.0.1
      - --tls-san=10.0.0.11
      - --tls-san=k3s.kuiperdesk.com
      - --token=kuiperde5k-cluster-token
      - --cluster-init
    extraAgentArgs: []
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: true
~

